/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: (typeof import('ant-design-vue/es'))['Button']
    AButtonGroup: (typeof import('ant-design-vue/es'))['ButtonGroup']
    AConfigProvider: (typeof import('ant-design-vue/es'))['ConfigProvider']
    ADrawer: (typeof import('ant-design-vue/es'))['Drawer']
    ALayout: (typeof import('ant-design-vue/es'))['Layout']
    ALayoutContent: (typeof import('ant-design-vue/es'))['LayoutContent']
    ALayoutFooter: (typeof import('ant-design-vue/es'))['LayoutFooter']
    ALayoutHeader: (typeof import('ant-design-vue/es'))['LayoutHeader']
    ALayoutSider: (typeof import('ant-design-vue/es'))['LayoutSider']
    AMenu: (typeof import('ant-design-vue/es'))['Menu']
    AMenuItem: (typeof import('ant-design-vue/es'))['MenuItem']
    ASelect: (typeof import('ant-design-vue/es'))['Select']
    ASelectOption: (typeof import('ant-design-vue/es'))['SelectOption']
    HelloWorld: (typeof import('./src/components/HelloWorld.vue'))['default']
    IconCommunity: (typeof import('./src/components/icons/IconCommunity.vue'))['default']
    IconDocumentation: (typeof import('./src/components/icons/IconDocumentation.vue'))['default']
    IconEcosystem: (typeof import('./src/components/icons/IconEcosystem.vue'))['default']
    IconSupport: (typeof import('./src/components/icons/IconSupport.vue'))['default']
    IconTooling: (typeof import('./src/components/icons/IconTooling.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    Setting: (typeof import('./src/components/setting/index.vue'))['default']
    SettingView: (typeof import('./src/components/setting/SettingView.vue'))['default']
    SettingWrapper: (typeof import('./src/components/setting/SettingWrapper.vue'))['default']
    TheWelcome: (typeof import('./src/components/TheWelcome.vue'))['default']
    WelcomeItem: (typeof import('./src/components/WelcomeItem.vue'))['default']
  }
}
