/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AiChat: typeof import('./../src/components/Ai/AiChat.vue')['default']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AResult: typeof import('ant-design-vue/es')['Result']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    AssistantBlock: typeof import('./../src/components/Ai/components/AssistantBlock.vue')['default']
    ATypographyText: typeof import('ant-design-vue/es')['TypographyText']
    BaseUpload: typeof import('./../src/components/upload/BaseUpload.vue')['default']
    BasicButton: typeof import('./../src/components/button/components/BasicButton.vue')['default']
    CommonTable: typeof import('./../src/components/table/CommonTable.vue')['default']
    CustomButton: typeof import('./../src/components/button/CustomButton.vue')['default']
    FormModal: typeof import('./../src/components/form/FormModal.tsx')['default']
    Motion: typeof import('./../src/components/functional/Motion.tsx')['default']
    OperationButtons: typeof import('./../src/components/button/OperationButtons.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./../src/components/form/SearchForm.vue')['default']
    StatisticCard: typeof import('./../src/components/statistic/StatisticCard.vue')['default']
    SvgIcon: typeof import('./../src/components/svgIcon/SvgIcon.vue')['default']
    TinymceEditor: typeof import('./../src/components/tinymce/TinymceEditor.vue')['default']
  }
}
