/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BasicButton: typeof import('./../src/components/button/components/BasicButton.vue')['default']
    CommonTable: typeof import('./../src/components/table/CommonTable.vue')['default']
    CustomButton: typeof import('./../src/components/button/CustomButton.vue')['default']
    PopConfirmButton: typeof import('./../src/components/button/components/PopConfirmButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatisticCard: typeof import('./../src/components/statistic/StatisticCard.vue')['default']
    SvgIcon: typeof import('./../src/components/svgicon/SvgIcon.vue')['default']
  }
}
